services:
  - type: web
    name: uptime-kuma
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3001
    disk:
      name: uptime-kuma-data
      mountPath: /app/data
      sizeGB: 1
